packages:
  - .

allowBuilds:
  '@google/genai': true
  '@prisma/engines': true
  esbuild: true
  netlify-cli: true
  prisma: true
  protobufjs: true
  sharp: true
  unix-dgram: false

overrides:
  deepmerge-ts: 8.0.2
  mysql2: 3.24.5
