import { createServer as nodeCreateServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { mkdir } from 'node:fs/promises';
import { extname, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes, randomUUID, scryptSync, timingSafeEqual, createHash } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';

const root = fileURLToPath(new URL('.', import.meta.url));
const port = Number(process.env.PORT || 4173);
const databasePath = process.env.QUOTE_DATABASE_PATH || resolve(root, 'work', 'quoteflow.sqlite');
const mime = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.txt':'text/plain; charset=utf-8'};
await mkdir(resolve(databasePath,'..'),{recursive:true});
const db = new DatabaseSync(databasePath);
db.exec(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,verified_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS organizations(id TEXT PRIMARY KEY,name TEXT NOT NULL,reporting_currency TEXT NOT NULL DEFAULT 'AED',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS memberships(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),organization_id TEXT NOT NULL REFERENCES organizations(id),role TEXT NOT NULL CHECK(role IN ('Owner','Admin','Sales Manager','Sales Rep','Viewer')),created_at TEXT NOT NULL,UNIQUE(user_id,organization_id));
CREATE TABLE IF NOT EXISTS settings(organization_id TEXT PRIMARY KEY REFERENCES organizations(id),data TEXT NOT NULL,quote_counter INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS customers(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),data TEXT NOT NULL,deleted_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS catalog_items(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),data TEXT NOT NULL,deleted_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rfqs(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),data TEXT NOT NULL,deleted_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS quotes(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),data TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,version INTEGER NOT NULL DEFAULT 1,snapshot TEXT,status TEXT NOT NULL,deleted_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS followups(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),data TEXT NOT NULL,deleted_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),data TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(id_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),organization_id TEXT NOT NULL REFERENCES organizations(id),expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS email_tokens(id_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),kind TEXT NOT NULL,expires_at TEXT NOT NULL,used_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS acceptances(id TEXT PRIMARY KEY,quote_id TEXT NOT NULL REFERENCES quotes(id),quote_version INTEGER NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,statement TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(quote_id));
CREATE TABLE IF NOT EXISTS demo_state(id TEXT PRIMARY KEY CHECK(id='demo'),data TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS customers_org ON customers(organization_id); CREATE INDEX IF NOT EXISTS catalog_org ON catalog_items(organization_id); CREATE INDEX IF NOT EXISTS rfqs_org ON rfqs(organization_id); CREATE INDEX IF NOT EXISTS quotes_org_status ON quotes(organization_id,status); CREATE INDEX IF NOT EXISTS followups_org_due ON followups(organization_id); CREATE INDEX IF NOT EXISTS memberships_user ON memberships(user_id);`);
const now=()=>new Date().toISOString();
const digest=(s)=>createHash('sha256').update(s).digest('hex');
const json=(res,status,value,headers={})=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers});res.end(JSON.stringify(value));};
function readBody(req,max=1024*1024){return new Promise((resolve,reject)=>{let data='',size=0;req.on('data',c=>{size+=c.length;if(size>max){reject(Object.assign(new Error('Request too large'),{status:413}));req.destroy();return;}data+=c;});req.on('end',()=>{try{resolve(data?JSON.parse(data):{});}catch{reject(Object.assign(new Error('Invalid JSON'),{status:400}));}});req.on('error',reject);});}
const roles=['Owner','Admin','Sales Manager','Sales Rep','Viewer'];
const authHits=new Map();
db.prepare("INSERT OR IGNORE INTO demo_state(id,data,updated_at) VALUES('demo','{}',?)").run(new Date().toISOString());
function session(req){const m=/qf_session=([^;]+)/.exec(req.headers.cookie||'');if(!m)return null;const row=db.prepare('SELECT user_id,organization_id FROM sessions WHERE id_hash=? AND expires_at>?').get(digest(decodeURIComponent(m[1])),now());if(!row)return null;return db.prepare('SELECT u.id user_id,u.email,o.id organization_id,o.name organization_name,o.reporting_currency,m.role FROM users u JOIN memberships m ON m.user_id=u.id JOIN organizations o ON o.id=m.organization_id WHERE u.id=? AND o.id=?').get(row.user_id,row.organization_id)||null;}
const can=(role,permission)=>({Owner:['settings:write','team:write','sales:write','sales:read','billing:write'],Admin:['settings:write','team:write','sales:write','sales:read'], 'Sales Manager':['sales:write','sales:read'],'Sales Rep':['sales:write','sales:read'],Viewer:['sales:read']}[role]||[]).includes(permission);
function audit(org,actor,action,object){db.prepare('INSERT INTO events(id,organization_id,data,created_at) VALUES(?,?,?,?)').run(randomUUID(),org,JSON.stringify({actor,action,object,at:now()}),now());}
function passwordHash(password,salt=randomBytes(16).toString('hex')){return `${salt}:${scryptSync(password,salt,64).toString('hex')}`;}
function validPassword(password){return typeof password==='string'&&password.length>=12&&password.length<=256;}
function quoteMath(q){const raw=q.items.reduce((s,i)=>s+Math.max(0,+i.qty||0)*Math.max(0,+i.price||0),0);const discount=Math.min(raw,Math.max(0,+q.discount||0));const net=raw-discount;const cost=q.items.reduce((s,i)=>s+Math.max(0,+i.qty||0)*Math.max(0,+i.cost||0),0);const tax=q.items.reduce((s,i)=>{const line=Math.max(0,+i.qty||0)*Math.max(0,+i.price||0);const allocated=raw?discount*line/raw:0;return s+Math.max(0,line-allocated)*Math.max(0,+i.tax||0)/100;},0);return{subtotal:net,tax,total:net+tax,cost,profit:net-cost,margin:net?(net-cost)/net*100:0};}
function collection(table,org){return db.prepare(`SELECT id,data FROM ${table} WHERE organization_id=? AND deleted_at IS NULL ORDER BY created_at DESC`).all(org).map(x=>({id:x.id,...JSON.parse(x.data)}));}
function persist(table,org,value){const id=value.id||randomUUID();const v={...value,id};db.prepare(`INSERT INTO ${table}(id,organization_id,data,created_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data WHERE ${table}.organization_id=excluded.organization_id`).run(id,org,JSON.stringify(v),now());return v;}
async function api(req,res,url){const path=url.pathname,method=req.method;try{
  if(path.startsWith('/api/auth/')&&['/api/auth/login','/api/auth/signup','/api/auth/recovery'].includes(path)){const key=req.socket.remoteAddress||'unknown',windowStart=Date.now(),entry=authHits.get(key)||{start:windowStart,count:0};if(windowStart-entry.start>60000){entry.start=windowStart;entry.count=0;}entry.count++;authHits.set(key,entry);if(entry.count>12)return json(res,429,{error:'Too many authentication requests. Wait a minute and try again.'},{'Retry-After':'60'});}
  if(!path.startsWith('/api/public/')&&!['GET','HEAD','OPTIONS'].includes(method)){const origin=req.headers.origin;if(origin&&origin!==`http://${req.headers.host}`&&origin!==`https://${req.headers.host}`)return json(res,403,{error:'Cross-origin request denied.'});}
  if(path==='/api/health'){return json(res,200,{ok:true,database:'sqlite-development-adapter',time:now()});}
  if(path==='/api/demo'&&method==='GET'){return json(res,200,JSON.parse(db.prepare("SELECT data FROM demo_state WHERE id='demo'").get().data));}
  if(path==='/api/demo'&&method==='PUT'){const b=await readBody(req,2_000_000);db.prepare("UPDATE demo_state SET data=?,updated_at=? WHERE id='demo'").run(JSON.stringify(b),now());return json(res,200,{ok:true});}
  if(path==='/api/demo/public'&&method==='GET'){const token=url.searchParams.get('token');const data=JSON.parse(db.prepare("SELECT data FROM demo_state WHERE id='demo'").get().data),q=(data.quotes||[]).find(x=>x.token===token);if(!q)return json(res,404,{error:'Quote link is invalid or unavailable.'});const customer=(data.customers||[]).find(x=>x.id===q.customerId),settings=data.settings||{};return json(res,200,{quote:{number:q.number,title:q.title,status:q.status,expiry:q.expiry,currency:q.currency,items:q.items.map(({name,sku,description,qty,unit,price,tax})=>({name,sku,description,qty,unit,price,tax})),totals:quoteMath(q),customer:{name:customer?.name,contact:customer?.contact,email:customer?.email},company:{name:settings.company,address:settings.address,email:settings.email,phone:settings.phone},terms:{payment:q.payment,delivery:q.delivery,notes:q.notes}}});}
  if(path==='/api/demo/public'&&method==='POST'){const b=await readBody(req),data=JSON.parse(db.prepare("SELECT data FROM demo_state WHERE id='demo'").get().data),q=(data.quotes||[]).find(x=>x.token===b.token);if(!q)return json(res,404,{error:'Quote link is invalid or unavailable.'});if(!['Sent','Viewed'].includes(q.status))return json(res,409,{error:'This quote already has a final response.'});if(!['accept','reject'].includes(b.action))return json(res,400,{error:'Unsupported response.'});if(b.action==='accept'&&(!String(b.name||'').trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(b.email||''))||b.agree!==true))return json(res,400,{error:'Name, valid email and agreement are required.'});q.status=b.action==='accept'?'Accepted':'Rejected';q.acceptedBy=b.action==='accept'?String(b.name).slice(0,160):undefined;q.acceptedAt=now();if(q.rfqId){const r=data.rfqs.find(x=>x.id===q.rfqId);if(r)r.status=b.action==='accept'?'Won':'Lost';}data.events.unshift({id:randomUUID(),action:`Quote ${q.status.toLowerCase()}`,object:q.number,actor:'Customer portal',at:now()});db.prepare("UPDATE demo_state SET data=?,updated_at=? WHERE id='demo'").run(JSON.stringify(data),now());return json(res,200,{status:q.status});}
  if(path==='/api/auth/signup'&&method==='POST'){const b=await readBody(req);const email=String(b.email||'').trim().toLowerCase(),password=b.password,orgName=String(b.organization||'').trim();if(!/^\S+@\S+\.\S+$/.test(email)||!validPassword(password)||orgName.length<2||orgName.length>120)return json(res,400,{error:'Enter a valid email, a 12-character password and an organization name.'});if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return json(res,409,{error:'An account already exists for this email.'});const user=randomUUID(),org=randomUUID(),at=now(),sid=randomBytes(32).toString('base64url');const tx=db.prepare('INSERT INTO users VALUES(?,?,?,?,?)');db.exec('BEGIN IMMEDIATE');try{tx.run(user,email,passwordHash(password),null,at);db.prepare('INSERT INTO organizations VALUES(?,?,?,?)').run(org,orgName,'AED',at);db.prepare('INSERT INTO memberships VALUES(?,?,?,?,?)').run(randomUUID(),user,org,'Owner',at);db.prepare('INSERT INTO settings(organization_id,data) VALUES(?,?)').run(org,JSON.stringify({company:orgName,currency:'AED',tax:5,margin:20,validity:30,payment:'30 days from invoice',delivery:'Delivery as agreed'}));db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?)').run(digest(sid),user,org,new Date(Date.now()+30*864e5).toISOString(),at);audit(org,user,'Organization created',orgName);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return json(res,201,{user:{email,role:'Owner'},organization:{id:org,name:orgName},onboardingRequired:true},{'Set-Cookie':`qf_session=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${30*86400}${process.env.NODE_ENV==='production'?'; Secure':''}`});}
  if(path==='/api/auth/login'&&method==='POST'){const b=await readBody(req),email=String(b.email||'').trim().toLowerCase(),u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!validPassword(b.password))return json(res,401,{error:'Email or password is incorrect.'});const [salt,hash]=u.password_hash.split(':');const actual=scryptSync(b.password,salt,64);if(!timingSafeEqual(actual,Buffer.from(hash,'hex')))return json(res,401,{error:'Email or password is incorrect.'});const member=db.prepare('SELECT organization_id FROM memberships WHERE user_id=? ORDER BY created_at LIMIT 1').get(u.id);if(!member)return json(res,403,{error:'This account has no organization membership.'});const sid=randomBytes(32).toString('base64url');db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?)').run(digest(sid),u.id,member.organization_id,new Date(Date.now()+30*864e5).toISOString(),now());return json(res,200,{user:{email:u.email}},{'Set-Cookie':`qf_session=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${30*86400}${process.env.NODE_ENV==='production'?'; Secure':''}`});}
  if(path==='/api/auth/logout'&&method==='POST'){const s=session(req);if(s){const m=/qf_session=([^;]+)/.exec(req.headers.cookie||'');if(m)db.prepare('DELETE FROM sessions WHERE id_hash=?').run(digest(decodeURIComponent(m[1])));}return json(res,200,{ok:true},{'Set-Cookie':'qf_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});}
  if(path==='/api/auth/me'){const s=session(req);return s?json(res,200,{user:{id:s.user_id,email:s.email},organization:{id:s.organization_id,name:s.organization_name,currency:s.reporting_currency},role:s.role}):json(res,401,{error:'Authentication required.'});}
  if(path==='/api/auth/recovery'&&method==='POST'){const b=await readBody(req);const email=String(b.email||'').trim().toLowerCase(),u=db.prepare('SELECT id FROM users WHERE email=?').get(email);if(!u)return json(res,200,{ok:true,message:'If this account exists, a recovery instruction can be sent once an email provider is configured.'});const token=randomBytes(32).toString('base64url');db.prepare('INSERT INTO email_tokens VALUES(?,?,?,?,NULL,?)').run(digest(token),u.id,'PASSWORD_RESET',new Date(Date.now()+30*60*1000).toISOString(),now());return json(res,202,{ok:true,message:'Recovery token created for development. Configure an email provider before production.',...(process.env.NODE_ENV==='production'?{}:{developmentToken:token})});}
  if(path==='/api/auth/reset-password'&&method==='POST'){const b=await readBody(req),row=db.prepare('SELECT * FROM email_tokens WHERE id_hash=? AND kind=\'PASSWORD_RESET\' AND used_at IS NULL AND expires_at>?').get(digest(String(b.token||'')),now());if(!row||!validPassword(b.password))return json(res,400,{error:'Recovery link is invalid or expired, or the new password is too short.'});db.exec('BEGIN IMMEDIATE');try{db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(passwordHash(b.password),row.user_id);db.prepare('UPDATE email_tokens SET used_at=? WHERE id_hash=?').run(now(),row.id_hash);db.prepare('DELETE FROM sessions WHERE user_id=?').run(row.user_id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return json(res,200,{ok:true});}
  if(path==='/api/auth/verify'&&method==='POST'){const b=await readBody(req),row=db.prepare('SELECT * FROM email_tokens WHERE id_hash=? AND kind=\'EMAIL_VERIFY\' AND used_at IS NULL AND expires_at>?').get(digest(String(b.token||'')),now());if(!row)return json(res,400,{error:'Verification link is invalid or expired.'});db.prepare('UPDATE users SET verified_at=? WHERE id=?').run(now(),row.user_id);db.prepare('UPDATE email_tokens SET used_at=? WHERE id_hash=?').run(now(),row.id_hash);return json(res,200,{ok:true});}
  if(path.startsWith('/api/public/quote/')){const token=path.split('/').pop(),hash=digest(token),row=db.prepare('SELECT id,organization_id,data,snapshot,status,version FROM quotes WHERE token_hash=? AND deleted_at IS NULL').get(hash);if(!row)return json(res,404,{error:'Quote link is invalid or unavailable.'});const q=JSON.parse(row.data);if(q.expiry&&q.expiry<now().slice(0,10))return json(res,410,{error:'This quotation has expired.'});if(method==='GET'){if(['Sent','Draft'].includes(q.status)){q.status='Viewed';db.prepare('UPDATE quotes SET data=?,status=? WHERE id=?').run(JSON.stringify(q),q.status,row.id);audit(row.organization_id,'Customer portal','Quote viewed',q.number);}const snapshot=JSON.parse(row.snapshot||'{}');return json(res,200,{quote:{number:q.number,title:q.title,status:q.status,expiry:q.expiry,currency:q.currency,items:snapshot.items||q.items,totals:snapshot.totals||quoteMath(q),customer:snapshot.customer,company:snapshot.company,terms:snapshot.terms}});}
    if(method==='POST'){const b=await readBody(req,16000);if(!['accept','reject'].includes(b.action))return json(res,400,{error:'Unsupported response.'});if(!['Sent','Viewed'].includes(q.status))return json(res,409,{error:'This quote already has a final response or is not available.'});if(b.action==='accept'&&(!String(b.name||'').trim()||!/^\S+@\S+\.\S+$/.test(String(b.email||''))||b.agree!==true))return json(res,400,{error:'Name, valid email and agreement are required.'});const org=row.organization_id;db.exec('BEGIN IMMEDIATE');try{q.status=b.action==='accept'?'Accepted':'Rejected';q.respondedAt=now();q.acceptedBy=b.action==='accept'?String(b.name).trim().slice(0,160):undefined;q.rejectionReason=String(b.reason||'').slice(0,1000);db.prepare('UPDATE quotes SET data=?,status=? WHERE id=? AND status IN (\'Sent\',\'Viewed\')').run(JSON.stringify(q),q.status,row.id);if(b.action==='accept')db.prepare('INSERT INTO acceptances VALUES(?,?,?,?,?,?,?)').run(randomUUID(),row.id,row.version,String(b.name).trim().slice(0,160),String(b.email).trim().slice(0,254),'I agree to the quotation and terms.',now());const linked=db.prepare('SELECT data FROM rfqs WHERE id=(SELECT json_extract(data,\'$.rfqId\') FROM quotes WHERE id=?) AND organization_id=?').get(row.id,org);if(linked){const rfq=JSON.parse(linked.data);rfq.status=b.action==='accept'?'Won':'Lost';db.prepare('UPDATE rfqs SET data=? WHERE id=(SELECT json_extract(data,\'$.rfqId\') FROM quotes WHERE id=?) AND organization_id=?').run(JSON.stringify(rfq),row.id,org);}audit(org,'Customer portal',`Quote ${q.status.toLowerCase()}`,q.number);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return json(res,200,{status:q.status});}return json(res,405,{error:'Method not allowed.'});}
  const s=session(req);if(!s)return json(res,401,{error:'Authentication required.'});const org=s.organization_id,role=s.role;const viewer=role==='Viewer';
  if(path==='/api/bootstrap'&&method==='GET'){const settings=JSON.parse(db.prepare('SELECT data FROM settings WHERE organization_id=?').get(org)?.data||'{}');const quotes=db.prepare('SELECT id,data FROM quotes WHERE organization_id=? AND deleted_at IS NULL ORDER BY created_at DESC').all(org).map(row=>{const q=JSON.parse(row.data);delete q.token;return {...q,id:row.id};});const products=collection('catalog_items',org).map(({cost,...p})=>p);return json(res,200,{settings,customers:collection('customers',org),products,rfqs:collection('rfqs',org),quotes,followups:collection('followups',org),events:db.prepare('SELECT data FROM events WHERE organization_id=? ORDER BY created_at DESC LIMIT 500').all(org).map(x=>JSON.parse(x.data)),user:{email:s.email,role},organization:{id:org,name:s.organization_name,currency:s.reporting_currency}});}
  if(path==='/api/settings'&&method==='PUT'){if(!can(role,'settings:write'))return json(res,403,{error:'Only an Owner or Admin may update settings.'});const b=await readBody(req);db.prepare('UPDATE settings SET data=? WHERE organization_id=?').run(JSON.stringify({...b,company:String(b.company||s.organization_name).slice(0,120)}),org);return json(res,200,{ok:true});}
  if(path==='/api/team'&&method==='GET'){if(!['Owner','Admin','Sales Manager'].includes(role))return json(res,403,{error:'Team access is not permitted.'});return json(res,200,{members:db.prepare('SELECT u.email,m.role,m.created_at FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=? ORDER BY m.created_at').all(org)});}
  if(path==='/api/team/invite'&&method==='POST'){if(!can(role,'team:write'))return json(res,403,{error:'Only an Owner or Admin may invite members.'});const b=await readBody(req),email=String(b.email||'').trim().toLowerCase(),targetRole=String(b.role||'Sales Rep');if(!/^\S+@\S+\.\S+$/.test(email)||!roles.includes(targetRole)||targetRole==='Owner')return json(res,400,{error:'Provide a valid email and a non-owner role.'});const user=db.prepare('SELECT id FROM users WHERE email=?').get(email);if(!user)return json(res,404,{error:'Invitee must create an account before joining. Email invitation is not configured.'});try{db.prepare('INSERT INTO memberships VALUES(?,?,?,?,?)').run(randomUUID(),user.id,org,targetRole,now());audit(org,s.user_id,'Team member added',email);return json(res,201,{ok:true});}catch(e){return json(res,409,{error:'This user may already belong to the organization.'});}}
  const maps={'customers':['customers','Customer created'],'products':['catalog_items','Catalog item saved'],'rfqs':['rfqs','RFQ saved'],'followups':['followups','Follow-up saved']};
  for(const [resource,[table,action]] of Object.entries(maps)){const base=`/api/${resource}`;if(path===base&&method==='GET')return json(res,200,{items:collection(table,org)});if(path===base&&method==='POST'){if(viewer)return json(res,403,{error:'Read-only role.'});const b=await readBody(req);if(!b||typeof b!=='object'||JSON.stringify(b).length>500000)return json(res,400,{error:'Invalid record.'});if(resource==='customers'&&!String(b.name||'').trim())return json(res,400,{error:'Customer name is required.'});if(resource==='products'&&(!String(b.name||'').trim()||+b.price<0||+b.cost<0))return json(res,400,{error:'Catalog name and non-negative prices are required.'});const value=persist(table,org,b);audit(org,s.user_id,action,value.number||value.name||value.title||value.id);return json(res,201,{item:value});}const id=path.slice(base.length+1);if(id&& !id.includes('/')&&method==='DELETE'){if(viewer)return json(res,403,{error:'Read-only role.'});const result=db.prepare(`UPDATE ${table} SET deleted_at=? WHERE id=? AND organization_id=? AND deleted_at IS NULL`).run(now(),id,org);return result.changes?json(res,200,{ok:true}):json(res,404,{error:'Record not found.'});}if(id&& !id.includes('/')&&method==='PUT'){if(viewer)return json(res,403,{error:'Read-only role.'});const existing=db.prepare(`SELECT id,data FROM ${table} WHERE id=? AND organization_id=? AND deleted_at IS NULL`).get(id,org);if(!existing)return json(res,404,{error:'Record not found.'});const b=await readBody(req);const value=persist(table,org,{...JSON.parse(existing.data),...b,id});return json(res,200,{item:value});}}
  if(path==='/api/quotes'&&method==='POST'){if(!can(role,'sales:write'))return json(res,403,{error:'Read-only role.'});const q=await readBody(req,500000);if(!String(q.title||'').trim()||!Array.isArray(q.items)||!q.items.length||q.items.some(i=>+i.qty<=0||+i.price<0||+i.cost<0||+i.tax<0||+i.tax>100))return json(res,400,{error:'Quote contains invalid or incomplete line items.'});if(!db.prepare('SELECT id FROM customers WHERE id=? AND organization_id=? AND deleted_at IS NULL').get(q.customerId,org))return json(res,404,{error:'Customer not found in this organization.'});if(q.rfqId&&!db.prepare('SELECT id FROM rfqs WHERE id=? AND organization_id=? AND deleted_at IS NULL').get(q.rfqId,org))return json(res,404,{error:'RFQ not found in this organization.'});const totals=quoteMath(q);if(+q.discount<0||+q.discount>q.items.reduce((n,i)=>n+i.qty*i.price,0))return json(res,400,{error:'Discount exceeds the subtotal.'});const settings=JSON.parse(db.prepare('SELECT data FROM settings WHERE organization_id=?').get(org)?.data||'{}');if(totals.margin<(+settings.margin||0)&&settings.marginMode==='Block')return json(res,409,{error:'Quote is below the minimum margin configured to block submission.'});if(totals.margin<(+settings.margin||0)&&settings.marginMode==='Approval Required'&&role==='Sales Rep')return json(res,409,{error:'This quote is below the margin guideline and requires manager review.'});if(q.id){const prev=db.prepare('SELECT id,data,status,snapshot FROM quotes WHERE id=? AND organization_id=? AND deleted_at IS NULL').get(q.id,org);if(!prev)return json(res,404,{error:'Quote not found.'});if(!['DRAFT','Draft','INTERNAL_REVIEW','Internal Review'].includes(prev.status))return json(res,409,{error:'Sent quotes are immutable. Create a revised quote instead.'});const old=JSON.parse(prev.data);q.token=undefined;q.number=old.number;q.status=old.status;q.organizationId=org;const updated={...old,...q};delete updated.token;db.prepare('UPDATE quotes SET data=?,status=?,version=version+1,snapshot=NULL WHERE id=? AND organization_id=?').run(JSON.stringify(updated),updated.status,q.id,org);audit(org,s.user_id,'Quote edited',updated.number);return json(res,200,{item:updated,totals});}const token=randomBytes(32).toString('base64url');q.id=randomUUID();q.organizationId=org;q.created=now().slice(0,10);db.exec('BEGIN IMMEDIATE');try{const row=db.prepare('UPDATE settings SET quote_counter=quote_counter+1 WHERE organization_id=? RETURNING quote_counter').get(org);if(!row)throw new Error('Organization settings unavailable.');q.number=`Q-${new Date().getUTCFullYear()}-${String(row.quote_counter).padStart(5,'0')}`;q.status='Draft';delete q.token;db.prepare('INSERT INTO quotes(id,organization_id,data,token_hash,version,status,created_at) VALUES(?,?,?,?,1,?,?)').run(q.id,org,JSON.stringify(q),digest(token),q.status,now());audit(org,s.user_id,'Quote created',q.number);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return json(res,201,{item:{...q,token},totals});}
  if(path.startsWith('/api/quotes/')&&method==='POST'&&path.endsWith('/send')){if(viewer)return json(res,403,{error:'Read-only role.'});const id=path.split('/')[3],row=db.prepare('SELECT data FROM quotes WHERE id=? AND organization_id=? AND deleted_at IS NULL').get(id,org);if(!row)return json(res,404,{error:'Quote not found.'});const q=JSON.parse(row.data);if(!['Draft','Internal Review'].includes(q.status))return json(res,409,{error:'Only a draft quote can be sent.'});const customer=db.prepare('SELECT data FROM customers WHERE id=? AND organization_id=? AND deleted_at IS NULL').get(q.customerId,org);if(!customer)return json(res,400,{error:'Customer is unavailable.'});const company=JSON.parse(db.prepare('SELECT data FROM settings WHERE organization_id=?').get(org)?.data||'{}');const snapshot={items:q.items.map(({name,sku,description,qty,unit,price,tax})=>({name,sku,description,qty,unit,price,tax})),totals:quoteMath(q),customer:JSON.parse(customer.data),company:{name:company.company,address:company.address,email:company.email,phone:company.phone},terms:{payment:q.payment,delivery:q.delivery,notes:q.notes}};q.status='Sent';q.sentAt=now();const token=randomBytes(32).toString('base64url');db.prepare('UPDATE quotes SET data=?,status=?,snapshot=?,token_hash=?,version=version+1 WHERE id=? AND organization_id=?').run(JSON.stringify(q),q.status,JSON.stringify(snapshot),digest(token),id,org);audit(org,s.user_id,'Quote sent (share link prepared; email provider not configured)',q.number);return json(res,200,{status:'Sent',publicUrl:`${process.env.APP_URL||`http://localhost:${port}`}/q/${token}`,token});}
  if(path==='/api/analytics'&&method==='GET'){const quotes=db.prepare('SELECT data FROM quotes WHERE organization_id=? AND deleted_at IS NULL').all(org).map(x=>JSON.parse(x.data));const byCurrency={};for(const q of quotes){const cur=q.currency||s.reporting_currency;(byCurrency[cur]??={quotes:0,quotedValue:0,wonValue:0,won:0,decided:0,marginTotal:0}).quotes++;const m=quoteMath(q);byCurrency[cur].quotedValue+=m.total;byCurrency[cur].marginTotal+=m.margin;if(['Accepted','Won'].includes(q.status)){byCurrency[cur].wonValue+=m.total;byCurrency[cur].won++;byCurrency[cur].decided++;}else if(['Rejected','Lost'].includes(q.status))byCurrency[cur].decided++;}return json(res,200,{reportingCurrency:s.reporting_currency,byCurrency:Object.fromEntries(Object.entries(byCurrency).map(([c,v])=>[c,{...v,winRate:v.decided?v.won/v.decided*100:0,averageMargin:v.quotes?v.marginTotal/v.quotes:0}]))});}
  return json(res,404,{error:'API route not found.'});
 }catch(e){console.error('api_error',e);return json(res,e.status||500,{error:e.status?e.message:'The request could not be completed.'});}}
export function createQuoteFlowServer(){return nodeCreateServer(async (req,res) => {
  const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return api(req,res,url);
  const pathname = decodeURIComponent(url.pathname);
  let file = resolve(root, `.${pathname}`);
  if (!file.startsWith(resolve(root)+sep) && file !== resolve(root,'index.html')) { res.writeHead(403); return res.end('Forbidden'); }
  try {
    if (pathname === '/' || pathname.startsWith('/q/') || pathname === '/login') file=resolve(root,'index.html');
    const body=await readFile(file);
    res.writeHead(200,{'Content-Type':mime[extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"});
    res.end(body);
  } catch { res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8','X-Content-Type-Options':'nosniff'}); res.end('Not found'); }
});}
if(process.env.QUOTEFLOW_NO_LISTEN!=='1')createQuoteFlowServer().listen(port,()=>console.log(`QuoteFlow demo listening at http://localhost:${port}`));
